source 'https://github.com/CocoaPods/Specs.git’
source 'https://github.com/migue19/NutPodSpecs.git’

target 'KavakTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KavakTest
  pod 'ConnectionLayer'
  pod 'NUTComponents'
end
